spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: demouser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    hiddenmethod:
      filter:
        enabled: true